# Generated by Django 4.0.5 on 2022-06-28 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle_tokenizer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='reg_number',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
