# Generated by Django 4.0.5 on 2022-06-29 02:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle_tokenizer', '0003_dealer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Dealer',
        ),
    ]
