# Generated by Django 4.0.5 on 2022-06-29 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle_tokenizer', '0004_delete_dealer'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='usage',
            field=models.IntegerField(default=0),
        ),
    ]
