# Generated by Django 4.0.5 on 2022-06-29 04:59

from django.db import migrations
import vehicle_tokenizer.models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle_tokenizer', '0005_vehicle_usage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='reg_number',
            field=vehicle_tokenizer.models.UpperCharField(max_length=20, unique=True),
        ),
    ]
